# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    zone:
        - { path: ^/api/* }
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '/api',  methods: ['GET', 'POST', 'DELETE', 'PUT'], priorities: ['json'], fallback_format: 'json' }
    body_listener:
        enabled: true
    allowed_methods_listener: true
